### ISSUE TITLE
Consider adding @your_username in the ?text=

### ISSUE THREAD

**Issue by jai-dewani** [saurabhdaware/blog.saurabhdaware.in#3]
This way you can be notified when someone shares your blog. 
https://github.com/saurabhdaware/blog.saurabhdaware.in/blob/f4bd5c4800da19db8b5f71bac9f1f27744b513a5/theme/components/TwitterShareButton.abell#L3-L9

**Comment by saurabhdaware** [comment]
ohh yup right makes sense! Thank you for suggesting!

**Comment by saurabhdaware** [comment]
Added it in some commit mid-way. Forgot when 🙈
